Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.network "forwarded_port", guest: 27017, host: 27017
    config.vm.network "private_network", ip: "192.168.33.14"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
    end
    config.vm.provision :shell, path: "bootstrap.sh"
  end